# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm install
    - run: npm update_readme
    - uses: actions/checkout@v3
    - run: |
        git config --global user.name leninner 
        git config --global user.name mazabandalenin180@gmail.com
        git add README.md
        git commit -m "Update README with latest blog posts"
        git push 
    
